# Generated by Django 5.1.15 on 2026-06-04 07:27

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetOpportunity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_name', models.CharField(help_text='Fund manager, Sacco, bank, or Treasury desk name.', max_length=120)),
                ('asset_class', models.CharField(choices=[('MMF', 'MMF'), ('SACCO_DEPOSIT', 'SACCO_DEPOSIT'), ('TREASURY_BILL', 'TREASURY_BILL'), ('UNIT_TRUST_EQUITY', 'UNIT_TRUST_EQUITY'), ('GOVERNMENT_BOND', 'GOVERNMENT_BOND'), ('CHAMA_CONTRIBUTION', 'CHAMA_CONTRIBUTION')], db_index=True, max_length=40)),
                ('annualised_yield_pct', models.DecimalField(decimal_places=2, help_text='Current annualised yield (%).', max_digits=5)),
                ('minimum_investment_kes', models.DecimalField(decimal_places=2, help_text='Minimum investment in Kenyan Shillings.', max_digits=14)),
                ('liquidity_days', models.PositiveSmallIntegerField(help_text='T+ days to access funds (0 = instant, 365 = long-lock).')),
                ('default_risk_pct', models.DecimalField(decimal_places=2, help_text='Historical or modelled default probability (%).', max_digits=5)),
                ('max_leverage_ratio', models.DecimalField(decimal_places=2, default=1.0, help_text='Maximum leverage ratio allowed on this instrument.', max_digits=5)),
                ('suitable_risk_tiers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), help_text="List of RiskTier values this asset suits (e.g., ['CONSERVATIVE','MODERATE']).", size=None)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only active opportunities are surfaced to agents.')),
                ('regulatory_note', models.TextField(blank=True, default='', help_text='CMA / CBK / SASRA compliance note for the ops team.')),
            ],
            options={
                'verbose_name': 'Asset Opportunity',
                'verbose_name_plural': 'Asset Opportunities',
                'db_table': 'ap_asset_opportunity',
                'ordering': ['-annualised_yield_pct'],
                'indexes': [models.Index(fields=['asset_class', 'is_active'], name='ap_asset_op_asset_c_25ea1b_idx'), models.Index(fields=['default_risk_pct'], name='ap_asset_op_default_5992e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExecutionLedger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(db_index=True, help_text='Correlation ID linking this record to IngestionTelemetry.')),
                ('income_pattern', models.CharField(choices=[('CHAMA_POOLED', 'CHAMA_POOLED'), ('HIGH_VELOCITY_LIQUID', 'HIGH_VELOCITY_LIQUID'), ('IRREGULAR_GIG', 'IRREGULAR_GIG'), ('LOW_VELOCITY_ACCUMULATION', 'LOW_VELOCITY_ACCUMULATION'), ('MEDIUM_VELOCITY_MIXED', 'MEDIUM_VELOCITY_MIXED')], max_length=40)),
                ('risk_tier', models.CharField(choices=[('CONSERVATIVE', 'CONSERVATIVE'), ('MODERATE', 'MODERATE'), ('GROWTH', 'GROWTH'), ('AGGRESSIVE', 'AGGRESSIVE')], max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FALLBACK_APPLIED', 'FALLBACK_APPLIED')], db_index=True, max_length=20)),
                ('fallback_applied', models.BooleanField(default=False, help_text='True when Node 4 overrode the Crew output with a safe fallback.')),
                ('overall_default_risk_pct', models.DecimalField(decimal_places=2, help_text='Blended portfolio default-risk % after Sentinel verification.', max_digits=5)),
                ('max_leverage_ratio', models.DecimalField(decimal_places=2, help_text='Highest leverage ratio in the verified portfolio.', max_digits=5)),
                ('sentinel_verdict', models.TextField(help_text='Human-readable one-line verdict from the Rank Sentinel.')),
                ('final_recommendations_json', models.JSONField(help_text='Serialised list of AssetRecommendationSchema dicts.')),
                ('compliance_checks_json', models.JSONField(help_text='Serialised list of ComplianceCheckSchema dicts.')),
                ('chain_of_thought_md', models.TextField(help_text='Full Markdown CoT trace from the CrewAI run.')),
                ('crew_run_duration_seconds', models.DecimalField(decimal_places=3, help_text='Wall-clock duration of the Node 3 CrewAI execution.', max_digits=8)),
                ('payload_checksum', models.CharField(help_text='SHA-256 of the serialised VerifiedAllocationSchema for tamper detection.', max_length=64)),
            ],
            options={
                'verbose_name': 'Execution Ledger Entry',
                'verbose_name_plural': 'Execution Ledger Entries',
                'db_table': 'ap_execution_ledger',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id'], name='ap_executio_session_26f91f_idx'), models.Index(fields=['status', 'fallback_applied'], name='ap_executio_status_a98e41_idx'), models.Index(fields=['risk_tier', 'income_pattern'], name='ap_executio_risk_ti_22d3c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='IngestionTelemetry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Correlation ID propagated through the entire pipeline.', primary_key=True, serialize=False)),
                ('balance_tier', models.PositiveSmallIntegerField(help_text='Discretised balance band (1–10).')),
                ('velocity_score', models.DecimalField(decimal_places=2, help_text='30-day normalised transaction velocity (0–100).', max_digits=5)),
                ('frequency_multiplier', models.DecimalField(decimal_places=3, help_text='Outbound / inbound transaction count ratio.', max_digits=6)),
                ('avg_transaction_size_tier', models.PositiveSmallIntegerField(help_text='Discretised average ticket size band (1–10).')),
                ('chama_participation_flag', models.BooleanField(default=False)),
                ('chama_contribution_tier', models.PositiveSmallIntegerField(default=0, help_text='Monthly Chama contribution band (0 = non-participant).')),
                ('mpesa_active_days_last_30', models.PositiveSmallIntegerField(help_text='Active M-Pesa days in the last 30 calendar days.')),
                ('bill_payment_regularity', models.DecimalField(decimal_places=3, help_text='Fraction of recurring bills paid on time (0.000–1.000).', max_digits=4)),
                ('raw_schema_hash', models.CharField(help_text="SHA-256 of the inbound payload's key set (no values).", max_length=64)),
                ('source_channel', models.CharField(default='api', help_text="Originating channel identifier (e.g., 'api', 'batch', 'webhook').", max_length=64)),
            ],
            options={
                'verbose_name': 'Ingestion Telemetry',
                'verbose_name_plural': 'Ingestion Telemetry Records',
                'db_table': 'ap_ingestion_telemetry',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['balance_tier', 'velocity_score'], name='ap_ingestio_balance_28717e_idx'), models.Index(fields=['chama_participation_flag'], name='ap_ingestio_chama_p_710f43_idx')],
            },
        ),
    ]
